### ISSUE TITLE
zephir build doesn't builds phalcon

### ISSUE THREAD

**Issue by sergeyklay** [zephir-lang/zephir#1113]
```
git clone --depth=1 git://github.com/phalcon/zephir.git
cd zephir
./install-json
./install -c
```

```
$ zephir version
0.9a-dev
```

```
git clone --depth=1 git://github.com/phalcon/cphalcon.git
cd cphalcon/
zephir build
```

```
...
Preparing for PHP compilation...
Preparing configuration file...
Compiling...
Installing...
Zephir\CompilerException: Internal extension compilation failed. Check compile-errors.log for more information

at Library/Compiler.php(1126)
#0 Library/Compiler.php(1187): Zephir\Compiler->install(Object(Zephir\Commands\CommandBuild), false)
#1 Library/Commands/CommandAbstract.php(101): Zephir\Compiler->build(Object(Zephir\Commands\CommandBuild))
#2 Library/Bootstrap.php(199): Zephir\Commands\CommandAbstract->execute(Object(Zephir\Config), Object(Zephir\Logger))
#3 compiler.php(21): Zephir\Bootstrap::boot()
#4 {main}
```

```
$ cat compile-errors.log
/bin/bash: /home/klay/projects/zephir/phalcon/cphalcon/ext/libtool: No such file or directory
/bin/bash: /home/klay/projects/zephir/phalcon/cphalcon/ext/libtool: No such file or directory
make: *** [phalcon.lo] Error 127
make: *** Waiting for unfinished jobs....
make: *** [kernel/main.lo] Error 127
/bin/bash: /home/klay/projects/zephir/phalcon/cphalcon/ext/libtool: No such file or directory
make: *** [phalcon.lo] Error 127
```

```
$ aptitude search libtool | grep 'i '
i   libtool                         - Generic library support script
```

**Comment by steffengy** [comment]
Any other information?
`/bin/bash: /home/klay/projects/zephir/phalcon/cphalcon/ext/libtool: No such file or directory`
hints a wrongly setup build environment. Do phalcon's tests still pass or is this a general problem?

**Comment by sergeyklay** [comment]
Fortunately I am unable to reproduce this issue
