### ISSUE TITLE
segmentation fault on preg_match

### ISSUE THREAD

**Issue by flip111** [zephir-lang/zephir#1172]
zep

```
namespace Seg1;

class SymbolicNameString
{
    public static function validateSymbolicNameString(string symbolicNameString) -> string
    {
        var regs;
        if !(preg_match("/([\\p{L}\\p{Sc}\\p{Nl}\\p{Pc}]+)|`([^`]*)`/u", symbolicNameString, regs)) {
            throw new \InvalidArgumentException("The SymbolicNameString is not valid.");
        }
        return ":(";
    }

}
```

php

``` php
$foo = new \Seg1\SymbolicNameString();
$foo->validateSymbolicNameString("bar");
```

gdb

```
Starting program: /usr/bin/php test.php
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".

Program received signal SIGSEGV, Segmentation fault.
0x00007ffff245cc41 in zval_isref_p (pz=0x0) at /usr/include/php5/Zend/zend.h:415
415     return pz->is_ref__gc;
(gdb) bt
#0  0x00007ffff245cc41 in zval_isref_p (pz=0x0) at /usr/include/php5/Zend/zend.h:415
#1  zephir_call_function_opt (fci=0x7fffffffa660, fci_cache=0x7fffffffa630, info=0x7fffffffa790) at /home/flip101/zep/seg1/ext/kernel/extended/fcall.c:1195
#2  0x00007ffff24573dc in zephir_call_user_function (object_pp=0x0, obj_ce=0x0, type=zephir_fcall_function, function_name=0x0, retval_ptr_ptr=0x7fffffffa828, cache_entry=0x0, 
    cache_slot=0, param_count=5, params=0x7fffffffa8b0, info=0x7fffffffa790) at /home/flip101/zep/seg1/ext/kernel/fcall.c:570
#3  0x00007ffff24576c3 in zephir_call_func_aparams (return_value_ptr=0x7fffffffa828, func_name=0x7ffff2468bcd "preg_match", func_length=10, cache_entry=0x0, cache_slot=0, 
    param_count=5, params=0x7fffffffa8b0) at /home/flip101/zep/seg1/ext/kernel/fcall.c:672
#4  0x00007ffff2454ec5 in zephir_preg_match (return_value=0x7ffff7fcba78, regex=0x7fffffffa9d0, subject=0x7ffff7fc9d70, matches=0x0, global=0, flags=0, offset=0)
    at /home/flip101/zep/seg1/ext/kernel/string.c:1322
#5  0x00007ffff24672d0 in zim_Seg1_SymbolicNameString_validateSymbolicNameString (ht=1, return_value=0x7ffff7fcba48, return_value_ptr=0x7ffff7f960c8, this_ptr=0x0, 
    return_value_used=0) at /home/flip101/zep/seg1/ext/seg1/symbolicnamestring.zep.c:44
#6  0x00000000006f80ea in dtrace_execute_internal (execute_data_ptr=<optimized out>, fci=<optimized out>, return_value_used=<optimized out>)
    at /build/php5-qbYJ0w/php5-5.6.11+dfsg/Zend/zend_dtrace.c:97
#7  0x00007ffff2d02054 in xdebug_execute_internal (current_execute_data=0x7ffff7f96180, fci=0x0, return_value_used=0)
    at /build/xdebug-eWA5rf/xdebug-2.3.3/xdebug-2.3.3/xdebug.c:1767
#8  0x00000000007b73d7 in zend_do_fcall_common_helper_SPEC (execute_data=<optimized out>) at /build/php5-qbYJ0w/php5-5.6.11+dfsg/Zend/zend_vm_execute.h:560
#9  0x0000000000746400 in execute_ex (execute_data=execute_data@entry=0x7ffff7f96180) at /build/php5-qbYJ0w/php5-5.6.11+dfsg/Zend/zend_vm_execute.h:363
#10 0x00000000006f7f91 in dtrace_execute_ex (execute_data=0x7ffff7f96180) at /build/php5-qbYJ0w/php5-5.6.11+dfsg/Zend/zend_dtrace.c:73
#11 0x00007ffff2d01762 in xdebug_execute_ex (execute_data=0x7ffff7f96180) at /build/xdebug-eWA5rf/xdebug-2.3.3/xdebug-2.3.3/xdebug.c:1644
#12 0x000000000070aaa0 in zend_execute_scripts (type=type@entry=8, retval=retval@entry=0x0, file_count=file_count@entry=3)
    at /build/php5-qbYJ0w/php5-5.6.11+dfsg/Zend/zend.c:1341
#13 0x00000000006a5c70 in php_execute_script (primary_file=primary_file@entry=0x7fffffffd210) at /build/php5-qbYJ0w/php5-5.6.11+dfsg/main/main.c:2597
#14 0x00000000007b9321 in do_cli (argc=2, argv=0xf217c0) at /build/php5-qbYJ0w/php5-5.6.11+dfsg/sapi/cli/php_cli.c:994
#15 0x0000000000463dbe in main (argc=2, argv=0xf217c0) at /build/php5-qbYJ0w/php5-5.6.11+dfsg/sapi/cli/php_cli.c:1378
```

```
PHP 5.6.11-1ubuntu3.1 (cli) 
Copyright (c) 1997-2015 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2015 Zend Technologies
    with Zend OPcache v7.0.6-dev, Copyright (c) 1999-2015, by Zend Technologies
    with Xdebug v2.3.3, Copyright (c) 2002-2015, by Derick Rethans
```

on ubuntu 15.10

not sure if i should be reporting any additional info to help

**Comment by flip111** [comment]
putting

```
var regs;
let regs = null;
```

fixes the problem. However it would be better if the zephir compiler warns about this case

**Comment by flip111** [comment]
Being able to write code that parses correctly but segfaults seems like a clear bug to me. Why is this not considered a bug?
