### ISSUE TITLE
PHP7, array and too many references

### ISSUE THREAD

**Issue by mruz** [zephir-lang/zephir#1220]
``` zep
class Di
{

    public function test(var parameters)
    {
        this->test2([parameters]);

        return this;
    }

    public function test2(array! parameters)
    {
        let parameters["href"] = "test";

        return this;
    }
}
```

``` php
$di = new Di();
$t = $di
    ->test('test0')
    ->test('test1')
    ->test('test2')
    ->test('test3');
var_dump($t);
```

https://github.com/phalcon/zephir/issues/1173#issuecomment-200348593

```
Program received signal SIGSEGV, Segmentation fault.
0x000055555589bb8d in _emalloc_56 ()
(gdb) bt
#0  0x000055555589bb8d in _emalloc_56 ()
#1  0x00005555559043cd in zend_array_dup ()
#2  0x00005555558da330 in _zval_copy_ctor_func ()
#3  0x00007ffff303fde2 in zephir_array_update_string (arr=arr@entry=0x7fffffffa310, index=index@entry=0x7ffff313bf91 "href", index_length=index_length@entry=4, 
    value=value@entry=0x7fffffffa320, flags=flags@entry=1280) at /root/tmp/framework/ext/kernel/array.c:516
#4  0x00007ffff30a3749 in zim_Ice_Di_test2 (execute_data=<optimized out>, return_value=0x7fffffffa620) at /root/tmp/framework/ext/ice/di.zep.c:368
#5  0x00007ffff3047147 in zephir_call_function_opt (fci=fci@entry=0x7fffffffa520, fci_cache=fci_cache@entry=0x7fffffffa4f0, info=info@entry=0x7fffffffa5e0, params=params@entry=0x7fffffffa680)
    at /root/tmp/framework/ext/kernel/extended/fcall.c:1150
#6  0x00007ffff3044001 in zephir_call_user_function (object_pp=0x7fffffffa690, obj_ce=<optimized out>, obj_ce@entry=0x555555ef9cb0, type=type@entry=zephir_fcall_method, 
    function_name=function_name@entry=0x0, retval_ptr=0x7fffffffa620, cache_entry=cache_entry@entry=0x0, cache_slot=cache_slot@entry=0, param_count=param_count@entry=1, 
    params=params@entry=0x7fffffffa680, info=info@entry=0x7fffffffa5e0) at /root/tmp/framework/ext/kernel/fcall.c:453
#7  0x00007ffff304454b in zephir_call_class_method_aparams (return_value_ptr=return_value_ptr@entry=0x0, ce=0x555555ef9cb0, type=type@entry=zephir_fcall_method, 
    object=object@entry=0x7fffffffa690, method_name=method_name@entry=0x7ffff313d03b "test2", method_len=method_len@entry=5, cache_entry=cache_entry@entry=0x0, cache_slot=cache_slot@entry=0, 
    param_count=param_count@entry=1, params=params@entry=0x7fffffffa680) at /root/tmp/framework/ext/kernel/fcall.c:653
#8  0x00007ffff30a2818 in zim_Ice_Di_test (execute_data=<optimized out>, return_value=0x7ffff5e13100) at /root/tmp/framework/ext/ice/di.zep.c:345
#9  0x000055555596e01e in ZEND_DO_FCALL_SPEC_HANDLER ()
#10 0x0000555555969deb in execute_ex ()
#11 0x000055555596a77f in zend_execute ()
#12 0x00005555558ddd0c in zend_execute_scripts ()
#13 0x0000555555830f6a in php_execute_script ()
#14 0x0000555555a43515 in do_cli ()
#15 0x0000555555a448e0 in main ()
```

**Comment by sergeyklay** [comment]
Confirm this issue. 

```
$ php -v
PHP 7.0.5-3+donate.sury.org~trusty+1 (cli) ( NTS )
Copyright (c) 1997-2016 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2016 Zend Technologies
    with Zend OPcache v7.0.6-dev, Copyright (c) 1999-2016, by Zend Technologies
    with Xdebug v2.4.0, Copyright (c) 2002-2016, by Derick Rethans
```

```
$ zephir version
0.9.2a-dev
```

**Comment by andresgutierrez** [comment]
Fixed in latest commit on master
