### ISSUE TITLE
Fatal error: Uncaught Error: Call to undefined function Zephir\zephir_parse_file()

### ISSUE THREAD

**Issue by surjit** [zephir-lang/zephir#1235]
```
root@ubuntu:/home/php-to-zephir/converted/Handlebars# zephir build
PHP Warning:  PHP Startup: Unable to load dynamic library '/home/zephir/Library/../parser/zephir_parser.so' - /home/zephir/Library/../parser/zephir_parser.so: undefined symbol: zval_used_for_init in Unknown on line 0

Fatal error: Uncaught Error: Call to undefined function Zephir\zephir_parse_file() in /home/zephir/Library/CompilerFile.php:173
Stack trace:
#0 /home/zephir/Library/CompilerFile.php(563): Zephir\CompilerFile->genIR(Object(Zephir\Compiler))
#1 /home/zephir/Library/Compiler.php(318): Zephir\CompilerFile->preCompile(Object(Zephir\Compiler))
#2 /home/zephir/Library/Compiler.php(357): Zephir\Compiler->preCompile('handlebars/auto...')
#3 /home/zephir/Library/Compiler.php(904): Zephir\Compiler->recursivePreCompile('handlebars')
#4 /home/zephir/Library/Compiler.php(1131): Zephir\Compiler->generate(Object(Zephir\Commands\CommandBuild))
#5 /home/zephir/Library/Compiler.php(1267): Zephir\Compiler->compile(Object(Zephir\Commands\CommandBuild), false)
#6 /home/zephir/Library/Compiler.php(1348): Zephir\Compiler->install(Object(Zephir\Commands\CommandBuild), false)
#7 /home/zephir/Library/Commands/CommandAbstract.php(108): Zephir\Compiler->build(Object(Zephir\Commands\CommandBuild))
#8 /home/zephir/Library/Bootstrap.php(200): Zephir\Com in /home/zephir/Library/CompilerFile.php on line 173
```

**Comment by crocodile2u** [comment]
If you have switched PHP version from php-7 to php-5.X or vice versa, you'll have to delete /home/zephir/parser/zephir_parser.so. My guess would be that it was compiled with a different version of PHP than the one you are using now.

**Comment by surjit** [comment]
ok thanks, I will try it
