### ISSUE TITLE
Zephir\ParseException: Syntax error

### ISSUE THREAD

**Issue by surjit** [zephir-lang/zephir#1236]
```
root@ubuntu:/home/php-to-zephir/converted/Handlebars# zephir build
Zephir\ParseException: Syntax error in /home/php-to-zephir/converted/Handlebars/handlebars/handlebars.zep on line 25

        protected myTokenizer;
    ----------------------^

at Library/CompilerFile.php(570)
#0 Library/Compiler.php(318): Zephir\CompilerFile->preCompile(Object(Zephir\Compiler))
#1 Library/Compiler.php(357): Zephir\Compiler->preCompile('handlebars/hand...')
#2 Library/Compiler.php(904): Zephir\Compiler->recursivePreCompile('handlebars')
#3 Library/Compiler.php(1131): Zephir\Compiler->generate(Object(Zephir\Commands\CommandBuild))
#4 Library/Compiler.php(1250): Zephir\Compiler->compile(Object(Zephir\Commands\CommandBuild), false)
#5 Library/Compiler.php(1331): Zephir\Compiler->install(Object(Zephir\Commands\CommandBuild), false)
#6 Library/Commands/CommandAbstract.php(108): Zephir\Compiler->build(Object(Zephir\Commands\CommandBuild))
#7 Library/Bootstrap.php(200): Zephir\Commands\CommandAbstract->execute(Object(Zephir\Config), Object(Zephir\Logger))
#8 compiler.php(21): Zephir\Bootstrap::boot()
#9 {main}

```

**Comment by surjit** [comment]
``` zephir
/**
 * Handlebars
 *
 * @category  Xamin
 * @package   Handlebars
 * @author    fzerorubigd <fzerorubigd@gmail.com>
 * @author    Behrooz Shabani <everplays@gmail.com>
 * @author    Mardix <https://github.com/mardix>
 * @copyright 2012 (c) ParsPooyesh Co
 * @copyright 2013 (c) Behrooz Shabani
 * @copyright 2014 (c) Mardix
 * @license   MIT
 * @link      http://voodoophp.org/docs/handlebars
 */
namespace Handlebars;

use Handlebars\Loader\StringLoader;
use Handlebars\Cache\Dummy;
use InvalidArgumentException;
class Handlebars
{
    protected static instance = null;
    const VERSION = "2.2";

    protected myTokenizer;

    protected parser;

    protected helpers;

    protected loader;

    protected partialsLoader;

    protected cache;

    protected escape = "htmlspecialchars";

    protected escapeArgs = [ENT_COMPAT, "UTF-8"];
    protected aliases = [];

    public function __construct(array options = []) -> void
    {
        if isset options["helpers"] {
            this->setHelpers(options["helpers"]);
        }
        if isset options["loader"] {
            this->setLoader(options["loader"]);
        }
        if isset options["partials_loader"] {
            this->setPartialsLoader(options["partials_loader"]);
        }
        if isset options["cache"] {
            this->setCache(options["cache"]);
        }
        if isset options["escape"] {
            if !(is_callable(options["escape"])) {
                throw new InvalidArgumentException("Handlebars Constructor \"escape\" option must be callable");
            }
            let this->escape = options["escape"];
        }
        if isset options["escapeArgs"] {
            if !(is_array(options["escapeArgs"])) {
                let options["escapeArgs"] =  [options["escapeArgs"]];
            }
            let this->escapeArgs = options["escapeArgs"];
        }
        if isset options["partials_alias"] && is_array(options["partials_alias"]) {
            let this->aliases = options["partials_alias"];
        }
    }

    /**
     * Shortcut 'render' invocation.
     *
     * Equivalent to calling `$handlebars->loadTemplate($template)->render($data);`
     *
     * @param string $template template name
     * @param mixed  $data     data to use as context
     * @return string Rendered template
     */
    public function render(string template, data) -> string
    {
        return this->loadTemplate(template)->render(data);
    }


    public static function factory(array options = []) -> <Handlebars>
    {
        if !(self::instance) {
            let self::instance =  new self(options);
        }
        return self::instance;
    }    

    /**
     * To invoke when this object is called as a function
     *
     * @param string $template template name
     * @param mixed  $data     data to use as context
     * @return string Rendered template
     */
    public function __invoke(string template, data) -> string
    {
        return this->render(template, data);
    }

    /**
     * Set helpers for current enfine
     *
     * @param Helpers $helpers handlebars helper
     *
     * @return void
     */
    public function setHelpers(<Helpers> helpers)
    {
        let this->helpers = helpers;
    }

    /**
     * Get helpers, or create new one if ther is no helper
     *
     * @return Helpers
     */
    public function getHelpers() -> <Helpers>
    {
        if !(isset this->helpers) {
            let this->helpers =  new Helpers();
        }
        return this->helpers;
    }

    /**
     * Add a new helper.
     *
     * @param string $name   helper name
     * @param mixed  $helper helper callable
     *
     * @return void
     */
    public function addHelper(string name, helper)
    {
        this->getHelpers()->add(name, helper);
    }

    /**
     * Get a helper by name.
     *
     * @param string $name helper name
     * @return callable Helper
     */
    public function getHelper(string name)
    {
        return this->getHelpers()->__get(name);
    }

    /**
     * Check whether this instance has a helper.
     *
     * @param string $name helper name
     * @return boolean True if the helper is present
     */
    public function hasHelper(string name) -> boolean
    {
        return this->getHelpers()->has(name);
    }

    /**
     * Remove a helper by name.
     *
     * @param string $name helper name
     * @return void
     */
    public function removeHelper(string name)
    {
        this->getHelpers()->remove(name);
    }

    /**
     * Set current loader
     *
     * @param Loader $loader handlebars loader
     * @return void
     */
    public function setLoader(<Loader> loader)
    {
        let this->loader = loader;
    }

    /**
     * get current loader
     *
     * @return Loader
     */
    public function getLoader() -> <Loader>
    {
        if !(isset this->loader) {
            let this->loader =  new StringLoader();
        }
        return this->loader;
    }

    /**
     * Set current partials loader
     *
     * @param Loader $loader handlebars loader
     * @return void
     */
    public function setPartialsLoader(<Loader> loader)
    {
        let this->partialsLoader = loader;
    }

    /**
     * get current partials loader
     *
     * @return Loader
     */
    public function getPartialsLoader() -> <Loader>
    {
        if !(isset this->partialsLoader) {
            let this->partialsLoader =  new StringLoader();
        }
        return this->partialsLoader;
    }

    /**
     * Set cache  for current engine
     *
     * @param Cache $cache handlebars cache
     * @return void
     */
    public function setCache(<Cache> cache)
    {
        let this->cache = cache;
    }

    /**
     * Get cache
     *
     * @return Cache
     */
    public function getCache() -> <Cache>
    {
        if !(isset this->cache) {
            let this->cache =  new Dummy();
        }
        return this->cache;
    }

    /**
     * Get current escape function
     *
     * @return callable
     */
    public function getEscape()
    {
        return this->escape;
    }

    /**
     * Set current escape function
     *
     * @param callable $escape function
     * @throws \InvalidArgumentException
     * @return void
     */
    public function setEscape(escape)
    {
        if !(is_callable(escape)) {
            throw new InvalidArgumentException("Escape function must be a callable");
        }
        let this->escape = escape;
    }

    /**
     * Get current escape function
     *
     * @return array
     */
    public function getEscapeArgs() -> array
    {
        return this->escapeArgs;
    }

    /**
     * Set current escape function
     *
     * @param array $escapeArgs arguments to pass as extra arg to function
     * @return void
     */
    public function setEscapeArgs(array escapeArgs)
    {
        if !(is_array(escapeArgs)) {
            let escapeArgs =  [escapeArgs];
        }
        let this->escapeArgs = escapeArgs;
    }

    /**
     * Set the Handlebars myTokenizer instance.
     *
     * @param myTokenizer $myTokenizer myTokenizer
     * @return void
     */
    public function setTokenizer(<Tokenizer> myTokenizer)
    {
        let this->myTokenizer = myTokenizer;
    }

    /**
     * Get the current Handlebars Tokenizer instance.
     *
     * If no Tokenizer instance has been explicitly specified, this method will
     * instantiate and return a new one.
     *
     * @return Tokenizer
     */
    public function getTokenizer() -> <Tokenizer>
    {
        if !(isset this->myTokenizer) {
            let this->myTokenizer =  new Tokenizer();
        }
        return this->myTokenizer;
    }

    /**
     * Set the Handlebars Parser instance.
     *
     * @param Parser $parser parser object
     * @return void
     */
    public function setParser(<Parser> parser)
    {
        let this->parser = parser;
    }

    /**
     * Get the current Handlebars Parser instance.
     *
     * If no Parser instance has been explicitly specified, this method will
     * instantiate and return a new one.
     *
     * @return Parser
     */
    public function getParser() -> <Parser>
    {
        if !(isset this->parser) {
            let this->parser =  new Parser();
        }
        return this->parser;
    }

    /**
     * Load a template by name with current template loader
     *
     * @param string $name template name
     *
     * @return Template
     */
    public function loadTemplate(string name) -> <Template>
    {
        var source, tree;

        let source =  this->getLoader()->load(name);
        let tree =  this->tokenize(source);
        return new Template(this, tree, source);
    }

    /**
     * Load a partial by name with current partial loader
     *
     * @param string $name partial name
     *
     * @return Template
     */
    public function loadPartial(string name) -> <Template>
    {
        var source, tree;

        if isset this->aliases[name] {
            let name = this->aliases[name];
        }
        let source =  this->getPartialsLoader()->load(name);
        let tree =  this->tokenize(source);
        return new Template(this, tree, source);
    }

    /**
     * Register partial alias
     *
     * @param string $alias   Partial alias
     * @param string $content The real value
     * @return void
     */
    public function registerPartial(string alias, string content)
    {
        let this->aliases[alias] = content;
    }

    /**
     * Un-register partial alias
     *
     * @param string $alias Partial alias
     * @return void
     */
    public function unRegisterPartial(string alias)
    {
        if isset this->aliases[alias] {
            unset this->aliases[alias];

        }
    }

    /**
     * Load string into a template object
     *
     * @param string $source string to load
     * @return Template
     */
    public function loadString(string source) -> <Template>
    {
        var tree;

        let tree =  this->tokenize(source);
        return new Template(this, tree, source);
    }

    /**
     * try to tokenize source, or get them from cache if available
     *
     * @param string $source handlebars source code
     * @return array handlebars parsed data into array
     */
    protected function tokenize(string source) -> array
    {
        var hash, tree, tokens;

        let hash =  md5(sprintf("version: %s, data : %s", self::VERSION, source));
        let tree =  this->getCache()->get(hash);
        if tree === false {
            let tokens =  this->getTokenizer()->scan(source);
            let tree =  this->getParser()->parse(tokens);
            this->getCache()->set(hash, tree);
        }
        return tree;
    }

}
```

**Comment by andresgutierrez** [comment]
You have to place all the properties together and all the consts together

**Comment by surjit** [comment]
``` zephir
protected static instance = null;
const VERSION = "2.2";
protected myTokenizer, parser, helpers, loader, partialsLoader, cache;
protected escape = "htmlspecialchars";
protected escapeArgs = [ENT_COMPAT, "UTF-8"];
protected aliases = [];
```

like this if not, please give me example

**Comment by kse300489** [comment]
``` zephir
const VERSION0 = "2.2";
const VERSION1 = "2.2";
const VERSION2 = "2.2";

protected static instance = null;
protected myTokenizer, parser, helpers, loader, partialsLoader, cache;
protected escape = "htmlspecialchars";
protected escapeArgs = [ENT_COMPAT, "UTF-8"];
protected aliases = [];
```

First consts, then properties.
