### ISSUE TITLE
Incorrect array initialization in ZendEngine3

### ISSUE THREAD

**Issue by sergeyklay** [zephir-lang/zephir#1239]
It seems build fails on Zephir code like :

``` zephir
array someVar = [
    "key" : true
];
```

or

``` zephir
var someVar = [
    "key" : true
];
```

or

``` zephir
var someVar;
let someVar = [
    "key" : true
];
```

This happens only for ZendEngine3

```
at Library/Compiler.php(1287)
#0 Library/Compiler.php(1358): Zephir\Compiler->install(Object(Zephir\Commands\CommandBuildDev), true)
#1 Library/Commands/CommandAbstract.php(108): Zephir\Compiler->buildDev(Object(Zephir\Commands\CommandBuildDev))
#2 Library/Bootstrap.php(200): Zephir\Commands\CommandAbstract->execute(Object(Zephir\Config), Object(Zephir\Logger))
#3 compiler.php(21): Zephir\Bootstrap::boot()
#4 {main}
/zephir/ext/kernel/memory.c: In function 'zephir_dump_memory_frame':
/zephir/ext/kernel/memory.c:589:5: warning: field width specifier '*' expects argument of type 'int', but argument 3 has type 'char *' [-Wformat=]
     case IS_STRING:   fprintf(stderr, "value=%*s (%d)\n", Z_STRVAL_P(var), Z_STRLEN_P(var)); break;
     ^
/zephir/ext/kernel/memory.c:589:5: warning: format '%s' expects argument of type 'char *', but argument 4 has type 'size_t' [-Wformat=]
/zephir/ext/kernel/memory.c:589:5: warning: format '%d' expects a matching 'int' argument [-Wformat=]
In file included from /usr/include/php/20151012/Zend/zend.h:35:0,
                 from /usr/include/php/20151012/main/php.h:36,
```

**Comment by sergeyklay** [comment]
can't reproduce
