### ISSUE TITLE
ZEPHIR_IS_FALSE bug

### ISSUE THREAD

**Issue by lscgzwd** [zephir-lang/zephir#1279]
`ZEPHIR_IS_FALSE` has  bug.

**PHP 7.0.8** 
zephir master newest.

I am very sure fileName is existed. and php -r "echo is_file(fileName);" output 1.

``` zephir
if is_file(fileName) == false {

   var_dump(is_file(fileName)); // it show me true

    echo "xyz";// if ZEPHIR_IS_FALSE  work ok, it must not exec this line; but it executed. 

 }
```

if I use `===` , like `is_file(fileName) === false` . it works ok.

**Comment by sergeyklay** [comment]
**Zephir** (latest commit from master)

``` zephir
namespace BoolIssue;

class Test
{
    public function testBool(varTrue, varFalse)
    {
        var var1 = true;
        var var2 = false;

        var_dump(
          varTrue == var1,
          varTrue === var1,
          varFalse == var2,
          varFalse === var2,
          varTrue != var2,
          varTrue !== var2,
          varFalse != var1,
          varFalse !== var1
        );
    }
}

```

**PHP 7.0.8 Test**

``` php
$test = new BoolIssue\Test;
// The same as
// $test->testBool(true, false);
$test->testBool(1, 0);
```

>  bool(false)
> php: symbol lookup error: /usr/lib/php/20151012/boolissue.so: undefined symbol: ZEPHIR_IS_BOOL_IDENTICAL
> Command exited with non-zero status 127

**PHP 5.6.23. Test**

``` sh
zephir fullclean && zephir builddev
```

```
Copying new kernel files...
Generating stubs...
Preparing for PHP compilation...
Preparing configuration file...
Compiling...
Installing...
Zephir\CompilerException: Internal extension compilation failed. Check compile-errors.log for more information

at Library/Compiler.php(1350)
#0 Library/Compiler.php(1424): Zephir\Compiler->install(Object(Zephir\Commands\CommandBuildDev), true)
#1 Library/Commands/CommandAbstract.php(108): Zephir\Compiler->buildDev(Object(Zephir\Commands\CommandBuildDev))
#2 Library/Bootstrap.php(200): Zephir\Commands\CommandAbstract->execute(Object(Zephir\Config), Object(Zephir\Logger))
#3 compiler.php(21): Zephir\Bootstrap::boot()
#4 {main}
In file included from /usr/include/php/20131226/main/php.h:40:0,
                 from /zephir/ext/boolissue/test.zep.c:6:
/zephir/ext/boolissue/test.zep.c: In function 'zim_boolissue_Test_testBool1':
./kernel/operators.h:46:59: error: 'IS_TRUE' undeclared (first use in this function)
 #define ZEPHIR_IS_BOOL_VALUE(op1, op2) ((Z_TYPE_P(op1) == IS_TRUE || Z_TYPE_P(op1) == IS_FALSE) && zephir_compare_strict_bool(op1, op2))
                                                           ^
/usr/include/php/20131226/Zend/zend_API.h:557:21: note: in definition of macro 'ZVAL_BOOL'
   Z_LVAL_P(__z) = ((b) != 0); \
                     ^
/zephir/ext/boolissue/test.zep.c:42:16: note: in expansion of macro 'ZEPHIR_IS_BOOL_VALUE'
  ZVAL_BOOL(_0, ZEPHIR_IS_BOOL_VALUE(varTrue, var1));
                ^
./kernel/operators.h:46:59: note: each undeclared identifier is reported only once for each function it appears in
 #define ZEPHIR_IS_BOOL_VALUE(op1, op2) ((Z_TYPE_P(op1) == IS_TRUE || Z_TYPE_P(op1) == IS_FALSE) && zephir_compare_strict_bool(op1, op2))
                                                           ^
/usr/include/php/20131226/Zend/zend_API.h:557:21: note: in definition of macro 'ZVAL_BOOL'
   Z_LVAL_P(__z) = ((b) != 0); \
                     ^
/zephir/ext/boolissue/test.zep.c:42:16: note: in expansion of macro 'ZEPHIR_IS_BOOL_VALUE'
  ZVAL_BOOL(_0, ZEPHIR_IS_BOOL_VALUE(varTrue, var1));
                ^
./kernel/operators.h:46:87: error: 'IS_FALSE' undeclared (first use in this function)
 #define ZEPHIR_IS_BOOL_VALUE(op1, op2) ((Z_TYPE_P(op1) == IS_TRUE || Z_TYPE_P(op1) == IS_FALSE) && zephir_compare_strict_bool(op1, op2))
                                                                                       ^
/usr/include/php/20131226/Zend/zend_API.h:557:21: note: in definition of macro 'ZVAL_BOOL'
   Z_LVAL_P(__z) = ((b) != 0); \
                     ^
/zephir/ext/boolissue/test.zep.c:42:16: note: in expansion of macro 'ZEPHIR_IS_BOOL_VALUE'
  ZVAL_BOOL(_0, ZEPHIR_IS_BOOL_VALUE(varTrue, var1));
                ^
make: *** [boolissue/test.lo] Error 1
In file included from /usr/include/php/20131226/main/php.h:40:0,
                 from /zephir/ext/boolissue/test.zep.c:6:
/zephir/ext/boolissue/test.zep.c: In function 'zim_boolissue_Test_testBool1':
./kernel/operators.h:46:59: error: 'IS_TRUE' undeclared (first use in this function)
 #define ZEPHIR_IS_BOOL_VALUE(op1, op2) ((Z_TYPE_P(op1) == IS_TRUE || Z_TYPE_P(op1) == IS_FALSE) && zephir_compare_strict_bool(op1, op2))
                                                           ^
/usr/include/php/20131226/Zend/zend_API.h:557:21: note: in definition of macro 'ZVAL_BOOL'
   Z_LVAL_P(__z) = ((b) != 0); \
                     ^
/zephir/ext/boolissue/test.zep.c:42:16: note: in expansion of macro 'ZEPHIR_IS_BOOL_VALUE'
  ZVAL_BOOL(_0, ZEPHIR_IS_BOOL_VALUE(varTrue, var1));
                ^
./kernel/operators.h:46:59: note: each undeclared identifier is reported only once for each function it appears in
 #define ZEPHIR_IS_BOOL_VALUE(op1, op2) ((Z_TYPE_P(op1) == IS_TRUE || Z_TYPE_P(op1) == IS_FALSE) && zephir_compare_strict_bool(op1, op2))
                                                           ^
/usr/include/php/20131226/Zend/zend_API.h:557:21: note: in definition of macro 'ZVAL_BOOL'
   Z_LVAL_P(__z) = ((b) != 0); \
                     ^
/zephir/ext/boolissue/test.zep.c:42:16: note: in expansion of macro 'ZEPHIR_IS_BOOL_VALUE'
  ZVAL_BOOL(_0, ZEPHIR_IS_BOOL_VALUE(varTrue, var1));
                ^
./kernel/operators.h:46:87: error: 'IS_FALSE' undeclared (first use in this function)
 #define ZEPHIR_IS_BOOL_VALUE(op1, op2) ((Z_TYPE_P(op1) == IS_TRUE || Z_TYPE_P(op1) == IS_FALSE) && zephir_compare_strict_bool(op1, op2))
                                                                                       ^
/usr/include/php/20131226/Zend/zend_API.h:557:21: note: in definition of macro 'ZVAL_BOOL'
   Z_LVAL_P(__z) = ((b) != 0); \
                     ^
/zephir/ext/boolissue/test.zep.c:42:16: note: in expansion of macro 'ZEPHIR_IS_BOOL_VALUE'
  ZVAL_BOOL(_0, ZEPHIR_IS_BOOL_VALUE(varTrue, var1));
                ^
make: *** [boolissue/test.lo] Error 1
```

@steffengy @andresgutierrez  Could you please take a look at this

**Comment by andresgutierrez** [comment]
Will take a look

**Comment by sergeyklay** [comment]
@steffengy This is bug?

**Comment by alisovpv** [comment]
zephir fullclean
zephir build --backend=ZendEngine3


Preparing for PHP compilation...
Preparing configuration file...
Compiling...
kernel/memory.h:123:38: warning: backslash and newline separated by space
 #define ZEPHIR_OBS_COPY_OR_DUP(z, v) \
                                      ^
In file included from kernel/fcall.h:26:0:
./kernel/memory.h:123:38: warning: backslash and newline separated by space
 #define ZEPHIR_OBS_COPY_OR_DUP(z, v) \
                                      ^
Installing...
Zephir\CompilerException: Internal extension compilation failed. Check compile-e                                                                                 rrors.log for more information

at Library/Compiler.php(1350)
#0 Library/Compiler.php(1414): Zephir\Compiler->install(Object(Zephir\Commands\C                                                                                 ommandBuild), false)
#1 Library/Commands/CommandAbstract.php(108): Zephir\Compiler->build(Object(Zeph                                                                                 ir\Commands\CommandBuild))
#2 Library/Bootstrap.php(200): Zephir\Commands\CommandAbstract->execute(Object(Z                                                                                 ephir\Config), Object(Zephir\Logger))
#3 compiler.php(21): Zephir\Bootstrap::boot()
#4 {main}

I corrected kernel / memory.h: 123: 38, remove the spaces. Then I run the installation of an owl and I see all the same.

**Comment by sergeyklay** [comment]
@alisovpv https://github.com/phalcon/zephir/pull/1284

**Comment by alisovpv** [comment]
Thanks, kernel / memory.h: 123 I corrected this error and no more, but the rest remained unchanged:

Preparing for PHP compilation...
Preparing configuration file...
Compiling...
Installing...
Zephir\CompilerException: Internal extension compilation failed. Check compile-errors.log for more information

at Library/Compiler.php(1350)
#0 Library/Compiler.php(1414): Zephir\Compiler->install(Object(Zephir\Commands\CommandBuild), false)
#1 Library/Commands/CommandAbstract.php(108): Zephir\Compiler->build(Object(Zephir\Commands\CommandBuild))
#2 Library/Bootstrap.php(200): Zephir\Commands\CommandAbstract->execute(Object(Zephir\Config), Object(Zephir\Logger))
#3 compiler.php(21): Zephir\Bootstrap::boot()
#4 {main}

**Comment by sergeyklay** [comment]
@alisovpv Create separated issue and provide code to reproduce

**Comment by andresgutierrez** [comment]
Fixed in master

**Comment by sergeyklay** [comment]
@andresgutierrez could you please provide a small test?

**Comment by andresgutierrez** [comment]
https://github.com/phalcon/zephir/commit/a6c99e093845ee221609350fca6416e6e1928b02
