### ISSUE TITLE
Globals support string config

### ISSUE THREAD

**Issue by wolftankk** [zephir-lang/zephir#1410]
I define a string/char/uchar value in the global section of config.json, 
```
Zephir\Exception: Unknown type 'string' for extension global 'http_address'

at Library/Compiler.php(1810)
#0 Library/Compiler.php(2068): Zephir\Compiler->processExtensionGlobals('consulate')
#1 Library/Compiler.php(1155): Zephir\Compiler->createProjectFiles('consulate')
#2 Library/Compiler.php(1206): Zephir\Compiler->generate(Object(Zephir\Commands\CommandCompile))
#3 Library/Commands/CommandAbstract.php(108): Zephir\Compiler->compile(Object(Zephir\Commands\CommandCompile))
#4 Library/Bootstrap.php(200): Zephir\Commands\CommandAbstract->execute(Object(Zephir\Config), Object(Zephir\Logger))
#5 compiler.php(21): Zephir\Bootstrap::boot()
#6 {main}
```

----

In #985, it has supported  to define a bool value in php.ini, so, can globals support string/real/int ?

http://docstore.mik.ua/orelly/weblinux2/php/ch14_12.htm

**Comment by sergeyklay** [comment]
Could you please provide config.json to reproduce

**Comment by wolftankk** [comment]
```json
{
        "http_address" : {
            "type" : "string",
            "default" : "127.0.0.1"
        },
        "http_token" : {
            "type" : "string",
            "default" : ""
        },
        "http_auth" : {
            "type" : "string",
            "default" : ""
        },
        "use_ssl" : {
            "type" : "bool",
            "default" : false,
            "ini-entry" : {
                "type" : "bool",
                "name" : "use_ssl"
            }
        },
        "enable_ssl_verify" : {
            "type" : "bool",
            "default" : true,
            "ini-entry" : {
                "type" : "bool",
                "name" : "enable_ssl_verify"
            }
        }
}
```

**Comment by aiddroid** [comment]
In Zephir, extension globals are restricted to simple scalar types like int/bool/double/char, etc. Complex types such as string/arrays/objects/resources aren’t allowed here.

see the doc https://docs.zephir-lang.com/en/latest/globals.html
