### ISSUE TITLE
SIGSEGV when using __invoke, two instances

### ISSUE THREAD

**Issue by maciejmrozinski** [zephir-lang/zephir#1522]
Hi,

While testing Zephir possibilities I found a bug resolving in SIGSEGV. Below You can get sample repository with test php and zep files: [repo](https://github.com/maciejmrozinski/zephir_sigsegv). I tried to create as small example as possible.

Expected result:
```
1
string
12
aaa
123
1
string
12
aaa
123

Process finished with exit code 0
```

Current result:
```
1
string
12
aaa
123
1

Process finished with exit code 139 (interrupted by signal 11: SIGSEGV)
```

There is some problem with accessing property in second instance of `Test2` class when `__invoke` method is used in not direct way `{func}()`. If we change code to execute some other method (or even `func->__invoke()`) we won't get any issues anymore.

May be related to #438 

Zephir version 0.9.7-960dd783a9

Why I want to create such code? I see this as nice way to refactor PHPs closures with `use` statement to  Zephir classes with `__construct` parameters. This logic is stripped from example to make it cleaner.

**Comment by sjinks** [comment]
```
Program received signal SIGSEGV, Segmentation fault.
0x00007fffed3ebf2f in zval_get_type (pz=0x0) at /home/vladimir/.phpenv/versions/7.0.17-zts-debug/include/php/Zend/zend_types.h:327
327             return pz->u1.v.type;
#0  0x00007fffed3ebf2f in zval_get_type (pz=0x0) at /home/vladimir/.phpenv/versions/7.0.17-zts-debug/include/php/Zend/zend_types.h:327
#1  0x00007fffed3ed2cd in zephir_read_property (result=0x7fffffff98f0, object=0x0, property_name=0x7fffed40494d "a", property_length=1, flags=4352) at /home/vladimir/workspace/zephir_sigsegv/ext/kernel/object.c:436
#2  0x00007fffed400c6c in zim_Aaa_Test2___invoke (execute_data=0x7fffee0131a0, return_value=0x7fffffff9d30) at /home/vladimir/workspace/zephir_sigsegv/ext/aaa/test2.zep.c:78
#3  0x0000555555d78cb1 in zend_call_function (fci=0x7fffffff9c40, fci_cache=0x7fffffff9c10) at /tmp/php-build/source/7.0.17/Zend/zend_execute_API.c:878
#4  0x00007fffed3f8e38 in zephir_call_user_function (object_pp=0x0, obj_ce=0x0, type=zephir_fcall_function, function_name=0x7fffffff9d90, retval_ptr=0x7fffffff9d30, cache_entry=0x7fffffff9b90, cache_slot=0, param_count=0, params=0x7fffffff9da0)
    at /home/vladimir/workspace/zephir_sigsegv/ext/kernel/fcall.c:376
#5  0x00007fffed3f92ed in zephir_call_zval_func_aparams (return_value_ptr=0x0, func_name=0x7fffffff9d90, cache_entry=0x0, cache_slot=0, param_count=0, params=0x7fffffff9da0) at /home/vladimir/workspace/zephir_sigsegv/ext/kernel/fcall.c:478
#6  0x00007fffed400454 in zim_Aaa_Test_process (execute_data=0x7fffee013140, return_value=0x7fffffff9fe0) at /home/vladimir/workspace/zephir_sigsegv/ext/aaa/test.zep.c:58
#7  0x0000555555d78cb1 in zend_call_function (fci=0x7fffffffa030, fci_cache=0x7fffffffa000) at /tmp/php-build/source/7.0.17/Zend/zend_execute_API.c:878
#8  0x00007fffed3f8e38 in zephir_call_user_function (object_pp=0x7fffee013100, obj_ce=0x555556930000, type=zephir_fcall_method, function_name=0x7fffffffa140, retval_ptr=0x0, cache_entry=0x7fffffff9f80, cache_slot=0, param_count=0, params=0x7fffffffa1d0)
    at /home/vladimir/workspace/zephir_sigsegv/ext/kernel/fcall.c:376
#9  0x00007fffed3f951a in zephir_call_class_method_aparams (return_value=0x0, ce=0x555556930000, type=zephir_fcall_method, object=0x7fffee013100, method_name=0x7fffed40473e "process", method_len=7, cache_entry=0x7fffffffa1a8, cache_slot=0, param_count=0,
    params=0x7fffffffa1d0) at /home/vladimir/workspace/zephir_sigsegv/ext/kernel/fcall.c:518
#10 0x00007fffed400261 in zim_Aaa_Test_start (execute_data=0x7fffee0130e0, return_value=0x7fffee0130d0) at /home/vladimir/workspace/zephir_sigsegv/ext/aaa/test.zep.c:38
#11 0x0000555555dffead in ZEND_DO_FCALL_SPEC_HANDLER () at /tmp/php-build/source/7.0.17/Zend/zend_vm_execute.h:842
#12 0x0000555555dfe7b4 in execute_ex (ex=0x7fffee013030) at /tmp/php-build/source/7.0.17/Zend/zend_vm_execute.h:414
#13 0x0000555555dfe9b5 in zend_execute (op_array=0x7fffee087000, return_value=0x0) at /tmp/php-build/source/7.0.17/Zend/zend_vm_execute.h:458
#14 0x0000555555d958b0 in zend_execute_scripts (type=8, retval=0x0, file_count=3) at /tmp/php-build/source/7.0.17/Zend/zend.c:1443
#15 0x0000555555cd0198 in php_execute_script (primary_file=0x7fffffffc900) at /tmp/php-build/source/7.0.17/main/main.c:2492
#16 0x0000555555e6e600 in do_cli (argc=2, argv=0x5555567dd600) at /tmp/php-build/source/7.0.17/sapi/cli/php_cli.c:977
#17 0x0000555555e6faa3 in main (argc=2, argv=0x5555567dd600) at /tmp/php-build/source/7.0.17/sapi/cli/php_cli.c:1347
```

**Comment by sjinks** [comment]
Here is the patch for ZE3 if you want to try it out, I will commit the fix later after I write a test case

```diff
diff --git a/kernels/ZendEngine3/fcall.c b/kernels/ZendEngine3/fcall.c
index 71cff03..1678dee 100644
--- a/kernels/ZendEngine3/fcall.c
+++ b/kernels/ZendEngine3/fcall.c
@@ -201,12 +201,13 @@ static void resolve_callable(zval* retval, zephir_call_type type, zend_class_ent
        } ZEND_HASH_FILL_END();
 }
 
-static void populate_fcic(zend_fcall_info_cache* fcic, zephir_call_type type, zend_class_entry* ce, zval *this_ptr)
+static void populate_fcic(zend_fcall_info_cache* fcic, zephir_call_type type, zend_class_entry* ce, zval *this_ptr, zval *func)
 {
        zend_class_entry* calling_scope;
-       fcic->initialized = 0;
+       fcic->initialized      = 0;
+       fcic->function_handler = NULL;
 
-       if (type == zephir_fcall_function) {
+       if (type == zephir_fcall_function && Z_TYPE_P(func) != IS_OBJECT) {
                fcic->initialized   = 1;
                fcic->called_scope  = NULL;
                fcic->calling_scope = NULL;
@@ -222,6 +223,7 @@ static void populate_fcic(zend_fcall_info_cache* fcic, zephir_call_type type, ze
        calling_scope = EG(scope);
 #endif
 
+       fcic->object = this_ptr ? Z_OBJ_P(this_ptr) : NULL;
        switch (type) {
                case zephir_fcall_parent:
                        if (UNEXPECTED(!calling_scope || !calling_scope->parent)) {
@@ -244,7 +246,15 @@ static void populate_fcic(zend_fcall_info_cache* fcic, zephir_call_type type, ze
                        break;
 
                case zephir_fcall_function:
-                       /* already handled */
+                       if (Z_TYPE_P(func) == IS_OBJECT) {
+                               if (Z_OBJ_HANDLER_P(func, get_closure) && Z_OBJ_HANDLER_P(func, get_closure)(func, &fcic->calling_scope, &fcic->function_handler, &fcic->object) == SUCCESS) {
+                                       fcic->called_scope = fcic->calling_scope;
+                                       break;
+                               }
+
+                               return;
+                       }
+
                        break;

                case zephir_fcall_ce:
@@ -253,6 +263,15 @@ static void populate_fcic(zend_fcall_info_cache* fcic, zephir_call_type type, ze
                        break;

                case zephir_fcall_method:
+                       if (Z_TYPE_P(func) == IS_OBJECT) {
+                               if (Z_OBJ_HANDLER_P(func, get_closure) && Z_OBJ_HANDLER_P(func, get_closure)(func, &fcic->calling_scope, &fcic->function_handler, &fcic->object) == SUCCESS) {
+                                       fcic->called_scope = fcic->calling_scope;
+                                       break;
+                               }
+
+                               return;
+                       }
+
                        fcic->calling_scope = Z_OBJCE_P(this_ptr);
                        fcic->called_scope  = fcic->calling_scope;
                        break;
@@ -262,7 +281,6 @@ static void populate_fcic(zend_fcall_info_cache* fcic, zephir_call_type type, ze
        }

        fcic->initialized = 1;
-       fcic->object = this_ptr ? Z_OBJ_P(this_ptr) : NULL;
 }

 /**
@@ -333,8 +351,11 @@ int zephir_call_user_function(zval *object_pp, zend_class_entry *obj_ce, zephir_
        fcic.initialized = 0;
        if (cache_entry && *cache_entry) {
        /* We have a cache record, initialize scope */
-               populate_fcic(&fcic, type, obj_ce, object_pp);
-               fcic.function_handler = *cache_entry;
+               populate_fcic(&fcic, type, obj_ce, object_pp, function_name);
+               if (!fcic.function_handler) {
+                       fcic.function_handler = *cache_entry;
+               }
+
                ZVAL_UNDEF(&fci.function_name);
        }
        else if ((cache_entry && !*cache_entry) || zephir_globals_ptr->cache_enabled) {
@@ -362,7 +383,7 @@ int zephir_call_user_function(zval *object_pp, zend_class_entry *obj_ce, zephir_
 #if 0
 /*
        fcic.initialized = 0;
-       if (Z_TYPE_P(callable) == IS_NULL) {
+       if (Z_TYPE(callable) == IS_NULL) {
                resolve_callable(&callable, type, (object_pp && type != zephir_fcall_ce ? Z_OBJCE_P(object_pp) : obj_ce), object_pp, function_name);
        }
 */
```

**Comment by maciejmrozinski** [comment]
Thx, I can wait for commited fix :)
