### ISSUE TITLE
Fatal error: Uncaught Error: Call to undefined function Zephir\utf8_decode() in /home/www/zephir/Library/Compiler.php:2023

### ISSUE THREAD

**Issue by Tinywan** [zephir-lang/zephir#1575]
### Phalcon
+ version 3.2.2
###  build
```
$ sudo zephir build -export-classes
PHP Fatal error:  Uncaught Error: Call to undefined function Zephir\utf8_decode() in /home/www/zephir/Library/Compiler.php:2023
Stack trace:
#0 /home/www/zephir/Library/Compiler.php(1011): Zephir\Compiler->createProjectFiles('phalcon')
#1 /home/www/zephir/Library/Compiler.php(1062): Zephir\Compiler->generate(Object(Zephir\Commands\CommandBuild))
#2 /home/www/zephir/Library/Compiler.php(1200): Zephir\Compiler->compile(Object(Zephir\Commands\CommandBuild), false)
#3 /home/www/zephir/Library/Compiler.php(1297): Zephir\Compiler->install(Object(Zephir\Commands\CommandBuild), false)
#4 /home/www/zephir/Library/Commands/CommandAbstract.php(107): Zephir\Compiler->build(Object(Zephir\Commands\CommandBuild))
#5 /home/www/zephir/Library/Bootstrap.php(200): Zephir\Commands\CommandAbstract->execute(Object(Zephir\Config), Object(Zephir\Logger))
#6 /home/www/zephir/compiler.php(22): Zephir\Bootstrap::boot()
#7 {main}
  thrown in /home/www/zephir/Library/Compiler.php on line 2023

Fatal error: Uncaught Error: Call to undefined function Zephir\utf8_decode() in /home/www/zephir/Library/Compiler.php:2023
Stack trace:
#0 /home/www/zephir/Library/Compiler.php(1011): Zephir\Compiler->createProjectFiles('phalcon')
#1 /home/www/zephir/Library/Compiler.php(1062): Zephir\Compiler->generate(Object(Zephir\Commands\CommandBuild))
#2 /home/www/zephir/Library/Compiler.php(1200): Zephir\Compiler->compile(Object(Zephir\Commands\CommandBuild), false)
#3 /home/www/zephir/Library/Compiler.php(1297): Zephir\Compiler->install(Object(Zephir\Commands\CommandBuild), false)
#4 /home/www/zephir/Library/Commands/CommandAbstract.php(107): Zephir\Compiler->build(Object(Zephir\Commands\CommandBuild))
#5 /home/www/zephir/Library/Bootstrap.php(200): Zephir\Commands\CommandAbstract->execute(Object(Zephir\Config), Object(Zephir\Logger))
#6 /home/www/zephir/compiler.php(22): Zephir\Bootstrap::boot()
#7 {main}
``

**Comment by sjinks** [comment]
http://php.net/manual/en/function.utf8-decode.php

You probably don't have XML Parser extension (php-xml)

**Comment by Tinywan** [comment]
@sjinks 
+  XML Parser extension  has install
```
libXML support | active
-- | --
libXML Compiled Version | 2.9.1
libXML Loaded Version | 20901
libXML streams | enabled
```
+  php cli
```
www@ubuntu1:~/phalcon-zephir/cphalcon$ php -v
PHP 7.0.22-2+ubuntu14.04.1+deb.sury.org+4 (cli) (built: Aug  4 2017 14:36:28) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2017 Zend Technologies
    with Zend OPcache v7.0.22-2+ubuntu14.04.1+deb.sury.org+4, Copyright (c) 1999-2017, by Zend Technologies
www@ubuntu1:~/phalcon-zephir/cphalcon$ php -m
[PHP Modules]
calendar
Core
ctype
date
exif
fileinfo
filter
ftp
gettext
hash
iconv
json
libxml
openssl
pcntl
pcre
PDO
Phar
posix
readline
Reflection
session
shmop
sockets
SPL
standard
sysvmsg
sysvsem
sysvshm
tokenizer
Zend OPcache
zlib

[Zend Modules]
Zend OPcache
```

**Comment by sergeyklay** [comment]
You have to install/enable xml extension:
```sh
sudo apt-get install php7.0-xml
```

**Comment by sjinks** [comment]
`php -m` should show `xml`, like this:

```
[PHP Modules]
calendar
Core
ctype
curl
date
dom
exif
fileinfo
filter
ftp
gd
geoip
gettext
hash
iconv
igbinary
imagick
imap
intl
json
libxml
mbstring
mcrypt
memcached
mysql
mysqli
mysqlnd
openssl
pcntl
pcre
PDO
pdo_mysql
pdo_sqlite
Phar
posix
readline
Reflection
session
shmop
SimpleXML
sockets
SPL
sqlite3
standard
sysvmsg
sysvsem
sysvshm
tokenizer
wddx
xml
xmlreader
xmlwriter
xsl
Zend OPcache
zip
zlib

[Zend Modules]
Zend OPcache
```

You may have it enabled for another SAPI (Apache, FPM) but not for cli.

**Comment by sjinks** [comment]
Hint: the file `/etc/php/7.0/cli/conf.d/15-xml.ini` should exist.

**Comment by Tinywan** [comment]
@sjinks @sergeyklay  Thanks, it is OK! 
+  `sudo apt-get install php7.0-xml`
```
Preparing for PHP compilation...
Preparing configuration file...
Compiling...
Installing...
Extension installed!
Add extension=phalcon.so to your php.ini
Don't forget to restart your web server
```
