### ISSUE TITLE
Invalid superglobal for _POST

### ISSUE THREAD

**Issue by mruz** [zephir-lang/zephir#1623]
```zep
public function hasValue(string name) -> boolean
    {
        // Check if there is a post value for the item
        if isset _POST[name] {
            return true;
        } else {
            // Check if there is a predefined value for it
            if isset this->values[name] {
                return true;
            }
        }

        return false;
    }
```

I'm getting `Invalid superglobal`:
```c
PHP_METHOD(Ice_Tag, hasValue) {

	zval *name_param = NULL, *_POST, _0$$4;
	zval name;
	zval *this_ptr = getThis();

	ZVAL_UNDEF(&name);
	ZVAL_UNDEF(&_0$$4);

	ZEPHIR_MM_GROW();
	zephir_get_global(&_POST, SL("_POST"));
	if (!_POST) {
		ZEPHIR_THROW_EXCEPTION_STR(zend_exception_get_default(), "Invalid superglobal");
		return;
	}
	zephir_fetch_params(1, 1, 0, &name_param);

	zephir_get_strval(&name, name_param);


	if (zephir_array_isset(_POST, &name)) {
		RETURN_MM_BOOL(1);
	} else {
		zephir_read_property(&_0$$4, this_ptr, SL("values"), PH_NOISY_CC | PH_READONLY);
		if (zephir_array_isset(&_0$$4, &name)) {
			RETURN_MM_BOOL(1);
		}
	}
	RETURN_MM_BOOL(0);

}
```

It was working few zephir versions before
```c
PHP_METHOD(Ice_Tag, hasValue) {

	zval *name_param = NULL, _POST, _0$$4;
	zval name;
	zval *this_ptr = getThis();

	ZVAL_UNDEF(&name);
	ZVAL_UNDEF(&_POST);
	ZVAL_UNDEF(&_0$$4);

	ZEPHIR_MM_GROW();
	zephir_get_global(&_POST, SL("_POST"));
	zephir_fetch_params(1, 1, 0, &name_param);

	zephir_get_strval(&name, name_param);


	if (zephir_array_isset(&_POST, &name)) {
		RETURN_MM_BOOL(1);
	} else {
		zephir_read_property(&_0$$4, this_ptr, SL("values"), PH_NOISY_CC | PH_READONLY);
		if (zephir_array_isset(&_0$$4, &name)) {
			RETURN_MM_BOOL(1);
		}
	}
	RETURN_MM_BOOL(0);

}
```

**Comment by sergeyklay** [comment]
@mruz Could you please provide worked Zephir version / commit

**Comment by mruz** [comment]
It was working on this one https://github.com/phalcon/zephir/commit/a5f585482bf9c1f6a37d8162936765ebb3d9bfea. I haven't tested later versions, just the latest one.

**Comment by sergeyklay** [comment]
@mruz I was managed to reproduce this issue

##### Code

```zep
namespace Test\Globals;

class Post {
    public function hasValue(string name) -> boolean {
        return isset _POST[name];
    }
}
```

##### Tests

The `$_POST` superglobal exists:

```php
$post = new Post();

var_dump(isset($_POST)); // true
var_dump($post->hasValue('abc')); // false
```

The `$_POST` superglobal does not exist exists:

```php
$post = new Post();

unset($_POST);
var_dump(isset($_POST)); // false
var_dump($post->hasValue('abc'));
/*
PHP Fatal error:  Uncaught Exception: Invalid superglobal in /home/klay/workspace/c/zephir/manual.php:23
Stack trace:
#0 /home/klay/workspace/c/zephir/manual.php(23): Test\Globals\Post->hasValue('abc')
#1 {main}
  thrown in /home/klay/workspace/c/zephir/manual.php on line 23

Fatal error: Uncaught Exception: Invalid superglobal in /home/klay/workspace/c/zephir/manual.php:23
Stack trace:
#0 /home/klay/workspace/c/zephir/manual.php(23): Test\Globals\Post->hasValue('abc')
#1 {main}
  thrown in /home/klay/workspace/c/zephir/manual.php on line 23
*/
```

Generated code for PHP 7.2.1
```c
PHP_METHOD(Test_Globals_Post, hasValue) {

	zval *name_param = NULL, *_POST;
	zval name;
	zval *this_ptr = getThis();

	ZVAL_UNDEF(&name);

	ZEPHIR_MM_GROW();
	zephir_get_global(&_POST, SL("_POST"));
	if (!_POST) {
		ZEPHIR_THROW_EXCEPTION_STR(zend_exception_get_default(), "Invalid superglobal");
		return;
	}
	zephir_fetch_params(1, 1, 0, &name_param);

	zephir_get_strval(&name, name_param);


	RETURN_MM_BOOL(zephir_array_isset(_POST, &name));

}
```

**Comment by Jurigag** [comment]
Not sure, but maybe it's about cli?

**Comment by sergeyklay** [comment]
@mruz Well, there is no $_POST superglobal. Should we trigger E_USER_NOTICE instead?

**Comment by mruz** [comment]
Hmm, manual is saying it is superglobal http://pl1.php.net/manual/en/reserved.variables.post.php#refsect1-reserved.variables.post-notes
> This is a 'superglobal', or automatic global, variable. This simply means that it is available in all scopes throughout a script. There is no need to do global $variable; to access it within functions or methods.

**Comment by Jurigag** [comment]
Maybe you have for some reason enable_post_data_reading set to 0?

**Comment by mruz** [comment]
No, I have a default value `var_dump(ini_get('enable_post_data_reading'));`
> string(1) "1"

**Comment by sergeyklay** [comment]
@mruz
> This is a 'superglobal', or automatic global, variable. This simply means that it is available in all scopes throughout a script.

In PHP but not in Zephir. Anyway even for PHP it is untruth as you can see:
```php
isset($_POST); // true

unset($_POST);
isset($_POST); // false
```

Just created a small workaround #1630. Could you please take a look?

**Comment by sergeyklay** [comment]
Fixed in the `development` branch. Feel free to open a new issue if the problem appears again. Thank you for contributing.
