### ISSUE TITLE
Can't compile

### ISSUE THREAD

**Issue by rodriguescr** [zephir-lang/zephir#1697]
I'm getting this error on compile:

```
PHP Fatal error:  Uncaught Error: Call to a member function isInitialized() on boolean in /root/zephir/Library/Optimizers/FunctionCall/PregMatchOptimizer.php:51
Stack trace:
#0 /root/zephir/Library/FunctionCall.php(259): Zephir\Optimizers\FunctionCall\PregMatchOptimizer->optimize(Array, Object(Zephir\FunctionCall), Object(Zephir\CompilationContext))
#1 /root/zephir/Library/FunctionCall.php(348): Zephir\FunctionCall->optimize('preg_match', Array, Object(Zephir\FunctionCall), Object(Zephir\CompilationContext))
#2 /root/zephir/Library/FunctionCall.php(683): Zephir\FunctionCall->_callNormal(Array, Object(Zephir\CompilationContext))
#3 /root/zephir/Library/Expression.php(354): Zephir\FunctionCall->compile(Object(Zephir\Expression), Object(Zephir\CompilationContext))
#4 /root/zephir/Library/Optimizers/EvalExpression.php(89): Zephir\Expression->compile(Object(Zephir\CompilationContext))
#5 /root/zephir/Library/Statements/IfStatement.php(36): Zephir\Optimizers\EvalExpression->optimize(Array, Object(Zephir\CompilationContext))
#6 /root in /root/zephir/Library/Optimizers/FunctionCall/PregMatchOptimizer.php on line 51
```

Below the code:

```zep
namespace Fw;

/**
 * Router
 */

class Router
{

    /**
    * Associative array of routes
    * @var array
    */
    protected routes = []{
      get
    };

    /**
     * Parameters from the matched route
     * @var array
     */
    protected params = []{
      get
    };

    /**
     * Match the routes into the routing table, setting the params
     * property if a route is found
     * @param  string url The route URL
     * @return boolean true if a match found, false otherwise
     */
    public function match(url)
    {

        var route = "";
        var params = "";

        for route, params in this->routes  {
            if (preg_match(route, url, matches)) {
                for key, match in matches {
                    if (is_string(key)) {
                      let  params[key] = match;
                    }
                }
                let this->params = params;
                return true;
            }
        }
        return false;
    }

    /**
    * Add a route to the routing table
    * @param string route The Route URL
    * @param array params Parameters (controller, action, etc)
    */
    public function add(route, params = [])
    {
        //echo route."<br>";
        let route = preg_replace("/\//", "\\/", route);
        //echo route."<br>";
        let route = preg_replace("/\{([a-z]+)\}/", "(?P<\1>[a-z-]+)", route);
        //echo route."<br>";
        let route = preg_replace("/\{([a-z]+):([^\}]+)\}/", "(?P<\1>\2)", route);
        let route = "/^" . route . "/i";

        let this->routes[route] = params;

    }

	protected function removeQueryStringVariables(url){
		if(url != ""){
			let parts = explode("&", url, 2);

			if(strpos(parts[0], "=") === false){
				let url = parts[0];
			}else{
				let url = "";
			}
		}
		return url;
	}
	/**
	 * Check if route exists and return the called class and method
	 * @param  string url The class name string
	 * @return
	 */
	public function dispatch(url){
		let url = this->removeQueryStringVariables(url);

		if (this->match(url)){
			let controller = this->params['controller'];
			let controller = this->convertToStudlyCaps(controller);

			if(key_exists('routeNamespace',this->params)){
				let routeNamespace = this->params["routeNamespace"];
				let routeNamespace = this->convertToStudlyCaps(routeNamespace);
				let controller = "App\Controllers\\routeNamespace\\controller";
			}else {
				let controller = "App\Controllers\\controller";
			}

			if (class_exists(controller)){
				let controller_object = new controller();

				let action = this->params["action"];
				let action = this->convertToCamelCase(action);

				if (is_callable([controller_object, action])){
					controller_object->action();
				}	else{
					echo "Method " . action . " in controller " . controller . " not found";
				}
			}
			else {
				echo "Controller class " . controller . " not found";
			}
		} else {
			echo "No route matched";
		}
	}

	/**
	 * Convert class name to Studly Caps format
	 * @param  string string The class name string
	 * @return string
	 */
	protected function convertToStudlyCaps(routeString){
		return str_replace(" ", "", ucwords(str_replace("-", " ", routeString)));
	}
	/**
	 * Convert the method name to Camel Case format
	 * @param  string string The method name
	 * @return string
	 */
	protected function convertToCamelCase(routeString){
		return lcfirst(this->convertToStudlyCaps(routeString));
	}

}
```

**Comment by sergeyklay** [comment]
@rodriguescr Someone from the @phalcon/zephir-team (or I) will take a look in the next days.

**Comment by sergeyklay** [comment]
@rodriguescr The `matches` variable should be declared before usage.

```diff
    public function match(url)
    {

        var route = "";
        var params = "";
+      array matches;

        for route, params in this->routes  {
            if (preg_match(route, url, matches)) {
                for key, match in matches {
                    if (is_string(key)) {
                      let  params[key] = match;
                    }
                }
                let this->params = params;
                return true;
            }
        }
        return false;
    }
```

However, I agree that the error message must be correct and clear. I'll fix the error message in the future releases.

**Comment by dschissler** [comment]
Oh boy, another non-reporting issue which has caught me is having a function variable named the same as a parameter.  PHP or Javascript helps out more for example by telling you that something is not correct with that value but Zephir fails with weird error messages.   Its caught me a few times during refactors and I end up having to comment out a bunch of code to find it.  Now I know to look for so when I see that weird error I know what it means.

**Comment by sergeyklay** [comment]
@dschissler Could you please create a new issue with code to reproduce? I'll try to sort out. Thank you
