### ISSUE TITLE
Initial test execution failed - Class 'Test\Oo\PropertyAccess' not found

### ISSUE THREAD

**Issue by juan-morales** [zephir-lang/zephir#1896]
When I try to execute the tests I get this ...
```
$ ./vendor/bin/simple-phpunit 

PHP Fatal error:  Uncaught Error: Class 'Test\Oo\PropertyAccess' not found in /home/usuario/proyectos/zephir/unit-tests/Extension/FcallTest.php:18
Stack trace:

#0 /home/usuario/proyectos/zephir/vendor/bin/.phpunit/phpunit-7.4/src/Util/FileLoader.php(57): include_once()
#1 /home/usuario/proyectos/zephir/vendor/bin/.phpunit/phpunit-7.4/src/Util/FileLoader.php(45): PHPUnit\Util\FileLoader::load('/home/usuario/p...')
#2 /home/usuario/proyectos/zephir/vendor/bin/.phpunit/phpunit-7.4/src/Framework/TestSuite.php(540): PHPUnit\Util\FileLoader::checkAndLoad('/home/usuario/p...')
#3 /home/usuario/proyectos/zephir/vendor/bin/.phpunit/phpunit-7.4/src/Framework/TestSuite.php(618): PHPUnit\Framework\TestSuite->addTestFile('/home/usuario/p...')
#4 /home/usuario/proyectos/zephir/vendor/bin/.phpunit/phpunit-7.4/src/Util/Configuration.php(1137): PHPUnit\Framework\TestSuite->addTestFiles(Array)
#5 /home/usuario/proyectos/zephir/vendor/bin/.phpunit/phpunit-7.4/src/Util/Configuration.php(1003): PHPUnit\Util\Configuration->getTestSuite(Object(DOMEl in /home/usuario/proyectos/zephir/unit-tests/Extension/FcallTest.php on line 18

Fatal error: Uncaught Error: Class 'Test\Oo\PropertyAccess' not found in /home/usuario/proyectos/zephir/unit-tests/Extension/FcallTest.php:18
Stack trace:
#0 /home/usuario/proyectos/zephir/vendor/bin/.phpunit/phpunit-7.4/src/Util/FileLoader.php(57): include_once()
#1 /home/usuario/proyectos/zephir/vendor/bin/.phpunit/phpunit-7.4/src/Util/FileLoader.php(45): PHPUnit\Util\FileLoader::load('/home/usuario/p...')
#2 /home/usuario/proyectos/zephir/vendor/bin/.phpunit/phpunit-7.4/src/Framework/TestSuite.php(540): PHPUnit\Util\FileLoader::checkAndLoad('/home/usuario/p...')
#3 /home/usuario/proyectos/zephir/vendor/bin/.phpunit/phpunit-7.4/src/Framework/TestSuite.php(618): PHPUnit\Framework\TestSuite->addTestFile('/home/usuario/p...')
#4 /home/usuario/proyectos/zephir/vendor/bin/.phpunit/phpunit-7.4/src/Util/Configuration.php(1137): PHPUnit\Framework\TestSuite->addTestFiles(Array)
#5 /home/usuario/proyectos/zephir/vendor/bin/.phpunit/phpunit-7.4/src/Util/Configuration.php(1003): PHPUnit\Util\Configuration->getTestSuite(Object(DOMEl in /home/usuario/proyectos/zephir/unit-tests/Extension/FcallTest.php on line 18
```

**Comment by sergeyklay** [comment]
@juancarmo Did you compile & install test extension?

**Comment by sergeyklay** [comment]
I'm closing this issue due to the lack of any reaction. I'll open it again if the need arises
