### ISSUE TITLE
Segmentation fault zim_Ice_Dump_output

### ISSUE THREAD

**Issue by mruz** [zephir-lang/zephir#2073]
I'm getting SIGSEGV when try to dump detailed i18n class 
```php
echo (new \Ice\Dump(true, true))->vars(new \Ice\I18n()); exit;
```

https://github.com/ice/framework/blob/dev/ice/dump.zep https://github.com/ice/framework/blob/dev/ice/i18n.zep
Will try to provide minimal code.

```
Program received signal SIGSEGV, Segmentation fault.
0x00007ffff625497c in zim_Ice_Dump_output () from /usr/lib64/php7/extensions/ice.so
(gdb) bt full              
#0  0x00007ffff625497c in zim_Ice_Dump_output () from /usr/lib64/php7/extensions/ice.so
No symbol table info available.
#1  0x0000555555c6f364 in zend_call_function ()
No symbol table info available.
#2  0x00007ffff61a02b6 in zephir_call_user_function.constprop () from /usr/lib64/php7/extensions/ice.so
No symbol table info available.
#3  0x00007ffff62e54d9 in zephir_call_class_method_aparams () from /usr/lib64/php7/extensions/ice.so
No symbol table info available.
#4  0x00007ffff625ed83 in zim_Ice_Dump_output () from /usr/lib64/php7/extensions/ice.so
No symbol table info available.
#5  0x0000555555c6f364 in zend_call_function ()
No symbol table info available.
#6  0x00007ffff61a02b6 in zephir_call_user_function.constprop () from /usr/lib64/php7/extensions/ice.so
No symbol table info available.
#7  0x00007ffff62e54d9 in zephir_call_class_method_aparams () from /usr/lib64/php7/extensions/ice.so
No symbol table info available.
#8  0x00007ffff625ed83 in zim_Ice_Dump_output () from /usr/lib64/php7/extensions/ice.so
No symbol table info available.
#9  0x0000555555c6f364 in zend_call_function ()
...
#7204 0x00007ffff625ed83 in zim_Ice_Dump_output () from /usr/lib64/php7/extensions/ice.so
No symbol table info available.
#7205 0x0000555555c6f364 in zend_call_function ()
No symbol table info available.
#7206 0x00007ffff61a02b6 in zephir_call_user_function.constprop () from /usr/lib64/php7/extensions/ice.so
No symbol table info available.
#7207 0x00007ffff62e54d9 in zephir_call_class_method_aparams () from /usr/lib64/php7/extensions/ice.so
No symbol table info available.
#7208 0x00007ffff625ed83 in zim_Ice_Dump_output () from /usr/lib64/php7/extensions/ice.so
No symbol table info available.
#7209 0x0000555555c6f364 in zend_call_function ()
No symbol table info available.
#7210 0x00007ffff61a02b6 in zephir_call_user_function.constprop () from /usr/lib64/php7/extensions/ice.so
No symbol table info available.
#7211 0x00007ffff62e54d9 in zephir_call_class_method_aparams () from /usr/lib64/php7/extensions/ice.so
No symbol table info available.
#7212 0x00007ffff625ed83 in zim_Ice_Dump_output () from /usr/lib64/php7/extensions/ice.so
No symbol table info available.
#7213 0x0000555555c6f364 in zend_call_function ()
No symbol table info available.
#7214 0x00007ffff61a02b6 in zephir_call_user_function.constprop () from /usr/lib64/php7/extensions/ice.so
No symbol table info available.
#7215 0x00007ffff62e54d9 in zephir_call_class_method_aparams () from /usr/lib64/php7/extensions/ice.so
No symbol table info available.
#7216 0x00007ffff62523ca in zim_Ice_Dump_variable () from /usr/lib64/php7/extensions/ice.so
No symbol table info available.
#7217 0x0000555555c6f364 in zend_call_function ()
No symbol table info available.
#7218 0x00007ffff61a02b6 in zephir_call_user_function.constprop () from /usr/lib64/php7/extensions/ice.so
No symbol table info available.
#7219 0x00007ffff62e54d9 in zephir_call_class_method_aparams () from /usr/lib64/php7/extensions/ice.so
No symbol table info available.
#7220 0x00007ffff6261619 in zim_Ice_Dump_one () from /usr/lib64/php7/extensions/ice.so
No symbol table info available.
#7221 0x0000555555c6f364 in zend_call_function ()
No symbol table info available.
#7222 0x00007ffff61a02b6 in zephir_call_user_function.constprop () from /usr/lib64/php7/extensions/ice.so
No symbol table info available.
#7223 0x00007ffff62e54d9 in zephir_call_class_method_aparams () from /usr/lib64/php7/extensions/ice.so
No symbol table info available.
#7224 0x00007ffff6254590 in zim_Ice_Dump_vars () from /usr/lib64/php7/extensions/ice.so
No symbol table info available.
#7225 0x0000555555c0281f in ?? ()
No symbol table info available.
#7226 0x0000555555ba98f8 in execute_ex ()
No symbol table info available.
#7227 0x0000555555bac53d in ?? ()
No symbol table info available.
#7228 0x0000555555c5ae1d in zend_execute_scripts ()
No symbol table info available.
#7229 0x0000555555cd8508 in php_execute_script ()
No symbol table info available.
#7230 0x0000555555babf85 in ?? ()
No symbol table info available.
#7231 0x0000555555b8c44b in ?? ()
No symbol table info available.
#7232 0x00007ffff7e1cceb in __libc_start_main () from /lib64/libc.so.6
No symbol table info available.
#7233 0x0000555555b8c61a in _start ()
```

**Comment by sergeyklay** [comment]
Yes, minimal code to reproduce will help a lot.

**Comment by mruz** [comment]
Not Zephir issue.
